import tkinter as tk

root = tk.Toplevel()
root.title("作者信息")

frmlt_0 = tk.Frame(root,width=500, height=10)
laber_1 = tk.Label(root,text = "本程序由")
laber_2 = tk.Label(root,text = "北京科技大学天津学院")
laber_3 = tk.Label(root,text = "计算机1903班")
laber_4 = tk.Label(root,text = "杨瑞冬")
laber_5 = tk.Label(root,text = "谭翔宇")
laber_6 = tk.Label(root,text = "李俊杰")
laber_7 = tk.Label(root,text = "王琪")
laber_8 = tk.Label(root,text = "郑敬聪")
laber_9 = tk.Label(root,text = "杨宇鹏")
laber_10 = tk.Label(root,text = "制作完成")
laber_11 = tk.Label(root,text = "仅供完成程序设计实践作业使用")
frmlt_0.grid(row=0, column=1,padx=1,pady=3,columnspan = 3)
laber_1.grid(row = 1, column = 2)
laber_2.grid(row = 2, column = 2)
laber_3.grid(row = 3, column = 2)
laber_4.grid(row = 4, column = 2)
laber_5.grid(row = 5, column = 2)
laber_6.grid(row = 6, column = 2)
laber_7.grid(row = 7, column = 2)
laber_8.grid(row = 8, column = 2)
laber_9.grid(row = 9, column = 2)
laber_10.grid(row = 10, column = 2)
laber_11.grid(row = 11, column = 2)

root.mainloop()
